### ISSUE TITLE
Research SSH hosting in a VM for the API

### ISSUE THREAD

**Issue by markdav-is** [EugTech/asset-inventory#11]
@johnrnelson would like to have SSH access to a lunix VM so he can install everything needed to run the node-based API.  @nohorse will contact MVP Studio to see what options are available at Continu.

**Comment by markdav-is** [comment]
@johnrnelson is investigating GCP as an option and how expensive that might be.

**Comment by johnrnelson** [comment]
Am working on building a test box. It's cheap enough to play with for a few months on my own dime but if anyone can provide a cheaper alternative then I'm all for it.

 
![Screen Shot 2019-03-21 at 2 58 40 PM](https://user-images.githubusercontent.com/1356291/54787706-d5ec3100-4be9-11e9-841f-fc65a8e623c0.png)

**Comment by markdav-is** [comment]
scott lively   [Today at 2:34 PM]
I haven’t talked to them about hosting anything other than our Kubernetes cluster. I’m not sure how that would go because our conversation involved re-purposing old hardware. Anything else would involve their VM stack I assume, which has a month licensing cost that they might have to eat. If they wouldn’t do it for free the VM licensing is not cheap.

1 reply

Mark Davis (mod)   [< 1 minute ago]
can you do an intro email and I'll follow-up with them on the details?

**Comment by markdav-is** [comment]
If we follow MVP guidance, they will push us toward docker.  I don't want to slow you down by adding that now, so I'll contact continue and see what options we have for SSH hosting civic projects.

**Comment by markdav-is** [comment]
![image](https://user-images.githubusercontent.com/311063/54788737-66784080-4bed-11e9-8953-46107b23cee5.png)
