### ISSUE TITLE
Doesn't this exist already?

### ISSUE THREAD

**Issue by ottoradke** [EugTech/asset-inventory#9]
What makes this **asset-inventory** directory different from something like https://siliconshire.org/?

**Comment by markdav-is** [comment]
good question!  The plan is to take shire data and bring it into this inventory.  There are two studies going on right now.  One is driven by an "innovation district" effort and the UO is following some parameters for what assets are in/out.  Eug is also going for a UNESCO designation and that's another set of parameters.  We'll have some tags for what studies include what assets.

**Comment by markdav-is** [comment]
the other issue with SS data is no API.  It would be nice to sync things eventually.
